name: Build Mimikatz

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  SOLUTION_PATH:  'mimikatz.sln'
  MSBUILD_PATH: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\MSBuild.exe'

jobs:
  build:
    name: Build Mimikatz
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Build Tools
        shell: cmd
        run: |
          "vs_installer.exe" modify --installPath "C:\Program Files\Microsoft Visual Studio\2022\Preview" --add Microsoft.VisualStudio.Component.WinXP --quiet --norestart --nocache

      - name: Build Mimikatz
        run: |
          & "${{ env.MSBUILD_PATH }}" $Env:GITHUB_WORKSPACE\${{ env.SOLUTION_PATH }} /t:Build /p:'Configuration=Release;Platform=x64' /p:OutputPath=output
          dir
          dir output
