name: Build Mimikatz

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  SOLUTION_PATH: 'mimikatz.sln'
  MSBUILD_PATH: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\MSBuild.exe'

jobs:
  build:
    name: Build Mimikatz
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test
        shell: cmd
        # if: false
        run: |
          set
          dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC"
          dir "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0"
          reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\4.0" /v "VCTargetsPath" /d "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0" /f
          reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\MSBuild\ToolsVersions\4.0" /v "VCTargetsPath" /d "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0" /f
          reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\4.0" /v "VCTargetsPath"
          reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\MSBuild\ToolsVersions\4.0" /v "VCTargetsPath"

      - name: Install Build Tools
        shell: cmd
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify --installPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" --add Microsoft.VisualStudio.Component.WinXP --quiet --norestart --nocache

      

      - name: Build Mimikatz # C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v141
        continue-on-error: true
        run: |
          [Environment]::SetEnvironmentVariable("VCTargetsPath", "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140", "Machine")
          & "${{ env.MSBUILD_PATH }}" $Env:GITHUB_WORKSPACE\${{ env.SOLUTION_PATH }} /t:Build /p:'Configuration=Release;Platform=x64'
          dir
          dir x64

      - name: Store Build
        # if: github.event.inputs.save
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v3
        with:
          name: mimikatz
          path: |
            x64\
